import Link from "next/link";
import { BookOpenCheck, LayoutDashboard, Plus, Settings } from "lucide-react";
import { CruxerLogo } from "@/components/cruxer-logo";
import { ThemeToggle } from "@/components/theme-toggle";
import { CommandPalette } from "@/components/command-palette";
import { cn } from "@/lib/utils";

const nav = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/dashboard/new", label: "New kit", icon: Plus }, { href: "/dashboard/practice", label: "Practice", icon: BookOpenCheck }];

export function DashboardShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen lg:grid lg:grid-cols-[264px_minmax(0,1fr)]"><a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 rounded-lg bg-surface px-3 py-2">Skip to content</a><aside className="hidden border-r bg-surface px-4 py-6 lg:flex lg:flex-col" aria-label="Workspace navigation"><CruxerLogo /><nav className="mt-12 space-y-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-[13px] font-medium text-muted-ink transition-colors hover:bg-surface-raised hover:text-ink"><Icon size={17} />{label}</Link>)}</nav><div className="mt-auto border-t pt-4"><Link href="/dashboard/settings" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-[13px] font-medium text-muted-ink hover:bg-surface-raised hover:text-ink"><Settings size={17} />Settings</Link></div></aside><div className="min-w-0"><header className="flex h-16 items-center justify-between border-b bg-surface px-4 sm:px-6 lg:px-8"><Link href="/dashboard" className="lg:hidden"><CruxerLogo /></Link><CommandPalette /><div className="flex items-center gap-2"><ThemeToggle /><span className="grid h-8 w-8 place-items-center rounded-full bg-violet/15 text-xs font-semibold text-violet" aria-label="Signed in user">U</span></div></header><main id="main" className="page-frame py-8 pb-24 sm:py-10 lg:pb-10">{children}</main><nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-3 border-t bg-surface/95 p-2 backdrop-blur lg:hidden" aria-label="Mobile workspace navigation">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={cn("grid min-h-12 place-items-center gap-0.5 rounded-xl text-[11px] font-medium text-muted-ink hover:bg-surface-raised")}><Icon size={17} />{label}</Link>)}</nav></div></div>;
}
