"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, CalendarDays, Clock3, Gauge, Plus, RefreshCw, Sparkles, TrendingUp } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { motion, useReducedMotion } from "motion/react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { api, apiErrorMessage, isUnauthenticated, type ActivityDay, type KitSummary, type User, type WorkspaceOverview } from "@/lib/api";
import { cn } from "@/lib/utils";

type ScreenState = "loading" | "ready" | "error";
gsap.registerPlugin(ScrollTrigger);
function browserTimeZone() { return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"; }
function relativeTime(value: string) { const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60_000)); return minutes < 1 ? "Updated just now" : minutes < 60 ? `Updated ${minutes}m ago` : `Updated ${Math.round(minutes / 60)}h ago`; }
function intensity(units: number) { return units <= 0 ? "bg-line" : units === 1 ? "bg-success/25" : units === 2 ? "bg-success/50" : units <= 4 ? "bg-success/75" : "bg-success"; }

export function DashboardOverview() {
  const [state, setState] = useState<ScreenState>("loading");
  const [user, setUser] = useState<User | null>(null);
  const [kits, setKits] = useState<KitSummary[]>([]);
  const [workspace, setWorkspace] = useState<WorkspaceOverview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => {
    setState("loading"); setError(null);
    try {
      const [{ user: sessionUser }, { kits: nextKits }, nextWorkspace] = await Promise.all([api.session(), api.listKits(), api.getWorkspaceOverview({ days: 35, timeZone: browserTimeZone() })]);
      setUser(sessionUser); setKits(nextKits); setWorkspace(nextWorkspace); setState("ready");
    } catch (cause) { if (isUnauthenticated(cause)) { window.location.assign("/login"); return; } setError(apiErrorMessage(cause)); setState("error"); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  if (state === "loading") return <DashboardSkeleton />;
  if (state === "error") return <section className="mx-auto max-w-xl py-16 text-center"><p className="eyebrow">Workspace unavailable</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">We could not load your dashboard.</h1><p className="mt-3 text-sm text-muted-ink">{error}</p><Button className="mt-6" onClick={() => void load()}><RefreshCw size={16} />Try again</Button></section>;
  const data = workspace!;
  const metrics = new Map(data.kits.map((kit) => [kit.kitId, kit]));
  const name = user?.name || user?.email.split("@")[0] || "there";
  return <DashboardReveal><div className="space-y-5"><section data-workspace-reveal className="relative overflow-hidden rounded-[2rem] border border-white/60 bg-[linear-gradient(130deg,hsl(var(--surface))_0%,hsl(var(--surface-raised))_58%,hsl(var(--signal)/0.1)_150%)] px-6 py-8 shadow-[0_18px_54px_hsl(var(--ink)/0.08)] sm:px-9 sm:py-10"><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-signal/20 blur-3xl" aria-hidden="true" /><div className="absolute bottom-0 left-[42%] h-px w-1/2 bg-gradient-to-r from-transparent via-violet/30 to-transparent" aria-hidden="true" /><div className="relative flex flex-wrap items-end justify-between gap-7"><div><p className="eyebrow text-signal">Your preparation workspace</p><h1 className="mt-2 text-[clamp(2.15rem,4.6vw,4rem)] font-semibold tracking-[-0.055em]">Welcome back, {name}.</h1><p className="editorial-title mt-5 max-w-2xl text-2xl leading-[1.05] sm:text-[2rem]">“Small, deliberate practice makes the hard conversation feel familiar.”</p></div><Link href="/dashboard/new"><Button className="shadow-[0_14px_30px_hsl(var(--signal)/0.28)]"><Plus size={16} />Create a kit</Button></Link></div></section>
    <section data-workspace-reveal className="grid gap-3 sm:grid-cols-2 xl:grid-cols-12" aria-label="Workspace totals"><Metric className="xl:col-span-3" icon={Sparkles} label="Active kits" value={data.overview.activeKits} detail="Roles in progress" /><Metric className="xl:col-span-3" icon={BookOpenCheck} label="Cards reviewed" value={`${data.overview.reviewedCards}/${data.overview.totalCards}`} detail="Across all active kits" /><Metric className="xl:col-span-2" icon={BarChart3} label="Overall progress" value={`${data.overview.progressPercent}%`} detail="Unique cards reviewed" /><Metric className="xl:col-span-2" icon={Gauge} label="Recall confidence" value={`${data.overview.confidencePercent}%`} detail="Latest card ratings" /><Metric className="xl:col-span-2" icon={CalendarDays} label="Prompts" value={data.overview.totalQuestions} detail="Ready to rehearse" /></section>
    <section data-workspace-reveal className="grid gap-5 xl:grid-cols-12"><Card className="relative overflow-hidden p-5 shadow-[0_14px_45px_hsl(var(--ink)/0.07)] sm:p-7 xl:col-span-7"><div className="absolute right-0 top-0 h-28 w-28 rounded-full bg-violet/10 blur-3xl" aria-hidden="true" /><div className="relative flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Combined readiness</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Progress across every active kit</h2></div><span className="rounded-full bg-signal/10 px-3 py-1 font-mono text-sm font-semibold text-signal">{data.overview.progressPercent}%</span></div><div className="relative mt-7 h-3 overflow-hidden rounded-full bg-line"><motion.div initial={{ width: 0 }} animate={{ width: `${data.overview.progressPercent}%` }} transition={{ duration: 0.8, ease: "easeOut" }} className="h-full rounded-full bg-[linear-gradient(90deg,hsl(var(--signal)),hsl(var(--violet)))]" /></div><p className="mt-3 text-xs text-muted-ink"><span className="font-medium text-ink">{data.overview.confidencePercent}% recall confidence</span> · latest saved rating for every card</p><div className="relative mt-7 space-y-4">{data.kits.length > 0 ? data.kits.map((kit) => <div key={kit.kitId}><div className="flex items-center justify-between gap-4 text-sm"><span className="min-w-0 truncate font-medium">{kit.company} · {kit.roleTitle}</span><span className="shrink-0 text-xs text-muted-ink">{kit.reviewedCards}/{kit.totalCards} cards · {kit.confidencePercent}% confidence</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-violet" style={{ width: `${kit.progressPercent}%` }} /></div></div>) : <p className="text-sm text-muted-ink">Create a kit to begin tracking preparation.</p>}</div></Card><EffortGraph activity={data.activity.series} /></section>
    <section data-workspace-reveal><div className="mb-4 flex items-end justify-between gap-4"><div><p className="eyebrow">Your kits</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Keep the next conversation in view.</h2></div><span className="rounded-full border bg-surface/70 px-3 py-1 text-xs text-muted-ink">{kits.length} {kits.length === 1 ? "kit" : "kits"}</span></div>{kits.length === 0 ? <EmptyState /> : <div className="grid gap-3 xl:grid-cols-2">{kits.map((kit) => <KitRow key={kit.id} kit={kit} progress={metrics.get(kit.id)} />)}</div>}</section>
  </div></DashboardReveal>;
}

function DashboardReveal({ children }: { children: React.ReactNode }) {
  const root = useRef<HTMLDivElement>(null);
  const reduceMotion = useReducedMotion();
  useGSAP(() => {
    if (reduceMotion || !root.current) return;
    const sections = gsap.utils.toArray<HTMLElement>("[data-workspace-reveal]", root.current);
    sections.forEach((section, index) => {
      gsap.fromTo(section, { autoAlpha: 0, y: 18 }, { autoAlpha: 1, y: 0, duration: 0.5, delay: index === 0 ? 0.04 : 0, ease: "power2.out", scrollTrigger: { trigger: section, start: "top 88%", once: true } });
    });
  }, { scope: root, dependencies: [reduceMotion] });
  return <div ref={root}>{children}</div>;
}

function Metric({ className, icon: Icon, label, value, detail }: { className?: string; icon: typeof Sparkles; label: string; value: string | number; detail: string }) { return <motion.div whileHover={{ y: -3 }} transition={{ duration: 0.16 }} className={className}><Card className="h-full p-5 shadow-[0_10px_32px_hsl(var(--ink)/0.05)]"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-ink">{label}</span><span className="grid h-8 w-8 place-items-center rounded-xl bg-signal/10 text-signal"><Icon size={16} /></span></div><p className="mt-5 text-2xl font-semibold tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs text-muted-ink">{detail}</p></Card></motion.div>; }
function EffortGraph({ activity }: { activity: ActivityDay[] }) { const [active, setActive] = useState<ActivityDay | undefined>(activity.at(-1)); return <Card className="relative overflow-hidden p-5 shadow-[0_14px_45px_hsl(var(--ink)/0.07)] sm:p-7 xl:col-span-5"><div className="absolute -right-12 -bottom-16 h-40 w-40 rounded-full bg-success/10 blur-3xl" aria-hidden="true" /><div className="relative flex items-start justify-between gap-3"><div><p className="eyebrow">Daily effort</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Your study rhythm</h2></div><span className="inline-flex items-center gap-1 text-xs text-success"><TrendingUp size={14} />5 weeks</span></div><div className="relative mt-7 overflow-x-auto"><div className="grid min-w-[18rem] grid-flow-col grid-rows-5 gap-1.5">{activity.map((day) => <button key={day.date} type="button" className={cn("h-7 w-7 rounded-[5px] ring-1 ring-inset ring-white/30 transition-transform hover:scale-110 focus-visible:scale-110", intensity(day.effortUnits))} onFocus={() => setActive(day)} onMouseEnter={() => setActive(day)} onClick={() => setActive(day)} aria-label={`${day.date}: ${day.effortUnits} effort units`} />)}</div></div><p className="relative mt-4 min-h-5 text-xs text-muted-ink">{active ? `${active.date}: ${active.effortUnits === 0 ? "No saved effort" : `${active.effortUnits} effort units`}.` : "No saved effort yet."}</p><div className="relative mt-3 flex items-center gap-1.5 text-[11px] text-muted-ink"><span>Less</span>{[0, 1, 2, 3, 5].map((value) => <i key={value} className={cn("h-3.5 w-3.5 rounded-[4px]", intensity(value))} />)}<span>More</span></div></Card>; }
function KitRow({ kit, progress }: { kit: KitSummary; progress?: WorkspaceOverview["kits"][number] }) { const status = kit.status === "ready" ? "ready" : kit.status === "generating" ? "researching" : kit.status === "failed" ? "attention" : "partial"; return <motion.div whileHover={{ y: -3 }} transition={{ duration: 0.16 }}><Card className="group h-full overflow-hidden p-5 shadow-[0_10px_32px_hsl(var(--ink)/0.05)] transition-colors hover:bg-surface-raised"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[15px] font-semibold">{kit.roleTitle || "Untitled role"}</p><p className="mt-1 text-sm text-muted-ink">{kit.company || "Company research pending"}</p></div><StatusPill status={status} /></div>{progress && <div className="mt-5"><div className="flex justify-between text-xs text-muted-ink"><span>{progress.reviewedCards}/{progress.totalCards} flashcards reviewed</span><span>{progress.progressPercent}% covered · {progress.confidencePercent}% confidence</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-violet" style={{ width: `${progress.progressPercent}%` }} /></div></div>}<div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-ink"><span className="inline-flex items-center gap-1.5"><Clock3 size={14} />{relativeTime(kit.updatedAt)}</span><Link href={`/dashboard/kits/${kit.id}`} className="ml-auto inline-flex items-center gap-1.5 font-semibold text-ink transition group-hover:text-signal">{kit.status === "generating" ? "View progress" : "Open kit"} <ArrowRight size={14} /></Link></div></Card></motion.div>; }
function EmptyState() { return <Card className="overflow-hidden p-6 sm:p-8"><p className="editorial-title max-w-xl text-3xl leading-none">Give Cruxer a role, a company, and the time you have.</p><p className="mt-4 max-w-lg text-sm leading-6 text-muted-ink">It will make its research and coverage visible so you know exactly what you are preparing for.</p><Link href="/dashboard/new" className="mt-6 inline-flex min-h-11 items-center gap-2 text-[13px] font-medium text-signal hover:text-signal-strong">Start a new kit <ArrowRight size={15} /></Link></Card>; }
function DashboardSkeleton() { return <div aria-busy="true" aria-label="Loading dashboard"><div className="h-3 w-36 animate-pulse rounded bg-line" /><div className="mt-4 h-10 w-80 max-w-full animate-pulse rounded bg-line" /><div className="mt-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="h-32 animate-pulse rounded-card border bg-surface-raised" />)}</div></div>; }
